"""drop speed column from base races, migrate to racial trait

Revision ID: 005957a8da7f
Revises: 8363bc616626
Create Date: 2026-07-31 15:21:50.739870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005957a8da7f'
down_revision: Union[str, Sequence[str], None] = '8363bc616626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_races', 'speed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_races', sa.Column('speed', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
