"""add class hit_dice, archetypes, and class option choices

Revision ID: 16a73a4bb545
Revises: 7e26ab2fc591
Create Date: 2026-07-29 19:34:47.956952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a73a4bb545'
down_revision: Union[str, Sequence[str], None] = '7e26ab2fc591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_class_options',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('base_class_id', sa.UUID(), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=False),
    sa.Column('choice', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_class_id'], ['base_classes.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('base_classes', sa.Column('hit_dice', sa.Integer(), nullable=True))
    op.add_column('base_classes', sa.Column('arch_class_of', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'base_classes', 'base_classes', ['arch_class_of'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'base_classes', type_='foreignkey')
    op.drop_column('base_classes', 'arch_class_of')
    op.drop_column('base_classes', 'hit_dice')
    op.drop_table('character_class_options')
    # ### end Alembic commands ###
