"""add prerequisite_text to base_feats

Revision ID: 17f6379b0125
Revises: c09f87a2a76f
Create Date: 2026-08-01 10:01:47.166257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f6379b0125'
down_revision: Union[str, Sequence[str], None] = 'c09f87a2a76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_feats', sa.Column('prerequisite_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_feats', 'prerequisite_text')
    # ### end Alembic commands ###
