"""add spell prepared/cast tracking

Revision ID: 1858db0c0b76
Revises: bd221c2daa16
Create Date: 2026-08-23 23:30:13.809757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1858db0c0b76'
down_revision: Union[str, Sequence[str], None] = 'bd221c2daa16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_spell_preparations',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('base_class_id', sa.UUID(), nullable=False),
    sa.Column('spell_id', sa.UUID(), nullable=False),
    sa.Column('prepared_count', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_class_id'], ['base_classes.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['base_spells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'base_class_id', 'spell_id')
    )
    op.add_column('base_class_spells_known', sa.Column('spells_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_class_spells_known', 'spells_per_day')
    op.drop_table('character_spell_preparations')
    # ### end Alembic commands ###
