"""add manifestation sub-choice to feats

Revision ID: 20789db57ee4
Revises: 23c6e6808cd3
Create Date: 2026-09-22 20:33:16.284128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20789db57ee4'
down_revision: Union[str, Sequence[str], None] = '23c6e6808cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_feats', sa.Column('manifestation_options', sa.JSON(), nullable=True))
    op.add_column('character_feats', sa.Column('chosen_manifestation', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('character_feats_level_id_feat_id_chosen_weapon_id_chosen_sk_key'), 'character_feats', type_='unique')
    op.create_unique_constraint(None, 'character_feats', ['level_id', 'feat_id', 'chosen_weapon_id', 'chosen_skill_id', 'chosen_skill_id_2', 'chosen_spell_school', 'chosen_manifestation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_feats', type_='unique')
    op.create_unique_constraint(op.f('character_feats_level_id_feat_id_chosen_weapon_id_chosen_sk_key'), 'character_feats', ['level_id', 'feat_id', 'chosen_weapon_id', 'chosen_skill_id', 'chosen_skill_id_2', 'chosen_spell_school'], postgresql_nulls_not_distinct=False)
    op.drop_column('character_feats', 'chosen_manifestation')
    op.drop_column('base_feats', 'manifestation_options')
    # ### end Alembic commands ###
