"""add option_choice_id to secondary class ability grants

Revision ID: 23c6e6808cd3
Revises: 3519b8f435c6
Create Date: 2026-09-17 21:59:45.231163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c6e6808cd3'
down_revision: Union[str, Sequence[str], None] = '3519b8f435c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_secondary_class_ability_grants', sa.Column('option_choice_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('base_secondary_class_ability__secondary_base_class_id_chara_key'), 'base_secondary_class_ability_grants', type_='unique')
    op.create_unique_constraint(None, 'base_secondary_class_ability_grants', ['secondary_base_class_id', 'character_level', 'ability_id', 'option_choice_id'])
    op.create_foreign_key(None, 'base_secondary_class_ability_grants', 'base_class_option_choices', ['option_choice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'base_secondary_class_ability_grants', type_='foreignkey')
    op.drop_constraint(None, 'base_secondary_class_ability_grants', type_='unique')
    op.create_unique_constraint(op.f('base_secondary_class_ability__secondary_base_class_id_chara_key'), 'base_secondary_class_ability_grants', ['secondary_base_class_id', 'character_level', 'ability_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('base_secondary_class_ability_grants', 'option_choice_id')
    # ### end Alembic commands ###
