"""add requires_active_ability_id to base_class_abilities

Revision ID: 2f57b03b9f99
Revises: a5c868344322
Create Date: 2026-08-21 16:58:10.381515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f57b03b9f99'
down_revision: Union[str, Sequence[str], None] = 'a5c868344322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_class_abilities', sa.Column('requires_active_ability_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'base_class_abilities', 'base_class_abilities', ['requires_active_ability_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'base_class_abilities', type_='foreignkey')
    op.drop_column('base_class_abilities', 'requires_active_ability_id')
    # ### end Alembic commands ###
