"""model flex ability choice via race replacement system

Revision ID: 4336985e6816
Revises: d8513c758c5e
Create Date: 2026-07-29 11:00:26.059983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4336985e6816'
down_revision: Union[str, Sequence[str], None] = 'd8513c758c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_ability_choices',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('ability_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['base_race_abilities.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'ability_id')
    )
    op.drop_column('characters', 'flex_ability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('flex_ability', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_table('character_ability_choices')
    # ### end Alembic commands ###
