"""add duration_rounds_per_level to base_spells

Revision ID: 433dcddc98b3
Revises: c08ef54b0f63
Create Date: 2026-09-05 18:18:06.268455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433dcddc98b3'
down_revision: Union[str, Sequence[str], None] = 'c08ef54b0f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_spells', sa.Column('duration_rounds_per_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_spells', 'duration_rounds_per_level')
    # ### end Alembic commands ###
