"""add is_light to base_items

Revision ID: 4f3a7dc5cbc9
Revises: 95385060526f
Create Date: 2026-08-22 00:19:35.146309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3a7dc5cbc9'
down_revision: Union[str, Sequence[str], None] = '95385060526f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_items', sa.Column('is_light', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_items', 'is_light')
    # ### end Alembic commands ###
