"""add option_choice_id to base_class_ability_grants

Revision ID: 62ebc8000faf
Revises: f35cb680066b
Create Date: 2026-07-30 17:13:31.869935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ebc8000faf'
down_revision: Union[str, Sequence[str], None] = 'f35cb680066b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_class_ability_grants', sa.Column('option_choice_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('base_class_ability_grants_base_class_id_ability_id_key'), 'base_class_ability_grants', type_='unique')
    op.create_unique_constraint(None, 'base_class_ability_grants', ['base_class_id', 'ability_id', 'option_choice_id'])
    op.create_foreign_key(None, 'base_class_ability_grants', 'base_class_option_choices', ['option_choice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'base_class_ability_grants', type_='foreignkey')
    op.drop_constraint(None, 'base_class_ability_grants', type_='unique')
    op.create_unique_constraint(op.f('base_class_ability_grants_base_class_id_ability_id_key'), 'base_class_ability_grants', ['base_class_id', 'ability_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('base_class_ability_grants', 'option_choice_id')
    # ### end Alembic commands ###
