"""add feat sub-choice schema

Revision ID: 6480e4dfea03
Revises: e083b27d5316
Create Date: 2026-08-03 11:04:16.168007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6480e4dfea03'
down_revision: Union[str, Sequence[str], None] = 'e083b27d5316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_feats', sa.Column('sub_choice_type', sa.String(length=32), nullable=True))
    op.add_column('character_feats', sa.Column('chosen_weapon_id', sa.UUID(), nullable=True))
    op.add_column('character_feats', sa.Column('chosen_skill_id', sa.UUID(), nullable=True))
    op.add_column('character_feats', sa.Column('chosen_spell_school', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('character_feats_level_id_feat_id_key'), 'character_feats', type_='unique')
    op.create_unique_constraint(None, 'character_feats', ['level_id', 'feat_id', 'chosen_weapon_id', 'chosen_skill_id', 'chosen_spell_school'])
    op.create_foreign_key(None, 'character_feats', 'base_skills', ['chosen_skill_id'], ['id'])
    op.create_foreign_key(None, 'character_feats', 'base_items', ['chosen_weapon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_feats', type_='foreignkey')
    op.drop_constraint(None, 'character_feats', type_='foreignkey')
    op.drop_constraint(None, 'character_feats', type_='unique')
    op.create_unique_constraint(op.f('character_feats_level_id_feat_id_key'), 'character_feats', ['level_id', 'feat_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('character_feats', 'chosen_spell_school')
    op.drop_column('character_feats', 'chosen_skill_id')
    op.drop_column('character_feats', 'chosen_weapon_id')
    op.drop_column('base_feats', 'sub_choice_type')
    # ### end Alembic commands ###
