"""add base_item_granted_spells table

Revision ID: 64e9cdd3cd66
Revises: 7c4cfbbfb5a8
Create Date: 2026-08-17 17:19:18.385102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e9cdd3cd66'
down_revision: Union[str, Sequence[str], None] = '7c4cfbbfb5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_item_granted_spells',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('spell_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['base_items.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['base_spells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'spell_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_item_granted_spells')
    # ### end Alembic commands ###
