"""add ability_increase to character_levels

Revision ID: 65ba5c3da7b3
Revises: f2d551a5b053
Create Date: 2026-08-04 17:32:56.857922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ba5c3da7b3'
down_revision: Union[str, Sequence[str], None] = 'f2d551a5b053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_levels', sa.Column('ability_increase', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_levels', 'ability_increase')
    # ### end Alembic commands ###
