"""add restores_spell_grade to base_items

Revision ID: 661eba40db85
Revises: b4a2e4c4fcaf
Create Date: 2026-08-29 16:03:45.976240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661eba40db85'
down_revision: Union[str, Sequence[str], None] = 'b4a2e4c4fcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_items', sa.Column('restores_spell_grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_items', 'restores_spell_grade')
    # ### end Alembic commands ###
