"""add secondary class support

Revision ID: 70f00a71041e
Revises: 661eba40db85
Create Date: 2026-09-03 20:54:08.268055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f00a71041e'
down_revision: Union[str, Sequence[str], None] = '661eba40db85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_secondary_class_ability_grants',
    sa.Column('secondary_base_class_id', sa.UUID(), nullable=False),
    sa.Column('character_level', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.UUID(), nullable=False),
    sa.Column('effective_level_offset', sa.Integer(), server_default='0', nullable=False),
    sa.Column('effective_level_divisor', sa.Integer(), server_default='1', nullable=False),
    sa.Column('effective_level_minimum', sa.Integer(), nullable=True),
    sa.Column('option_group_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['base_class_abilities.id'], ),
    sa.ForeignKeyConstraint(['secondary_base_class_id'], ['base_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secondary_base_class_id', 'character_level', 'ability_id')
    )
    op.add_column('characters', sa.Column('secondary_base_class_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_characters_secondary_base_class_id', 'characters', 'base_classes', ['secondary_base_class_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_characters_secondary_base_class_id', 'characters', type_='foreignkey')
    op.drop_column('characters', 'secondary_base_class_id')
    op.drop_table('base_secondary_class_ability_grants')
    # ### end Alembic commands ###
