"""add spell list source to base classes

Revision ID: 81b8186e80d6
Revises: 70f00a71041e
Create Date: 2026-09-04 13:04:46.788021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b8186e80d6'
down_revision: Union[str, Sequence[str], None] = '70f00a71041e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_classes', sa.Column('spell_list_source_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_base_classes_spell_list_source_id', 'base_classes', 'base_classes', ['spell_list_source_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_base_classes_spell_list_source_id', 'base_classes', type_='foreignkey')
    op.drop_column('base_classes', 'spell_list_source_id')
    # ### end Alembic commands ###
