"""add ac bonus and equip fields to items and gear

Revision ID: 8363bc616626
Revises: c1db7b240e9f
Create Date: 2026-07-31 13:33:08.323970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8363bc616626'
down_revision: Union[str, Sequence[str], None] = 'c1db7b240e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_items', sa.Column('ac_bonus', sa.Integer(), nullable=True))
    op.add_column('base_items', sa.Column('max_dex_bonus', sa.Integer(), nullable=True))
    op.add_column('character_gear', sa.Column('equipped_slot', sa.String(length=32), nullable=True))
    op.add_column('character_gear', sa.Column('enhancement', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('character_gear', sa.Column('properties', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('character_gear', 'enhancement', server_default=None)
    op.alter_column('character_gear', 'properties', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_gear', 'properties')
    op.drop_column('character_gear', 'enhancement')
    op.drop_column('character_gear', 'equipped_slot')
    op.drop_column('base_items', 'max_dex_bonus')
    op.drop_column('base_items', 'ac_bonus')
    # ### end Alembic commands ###
