"""add kensai weapon choice table and requires_weapon_choice column

Revision ID: 88702dc539a2
Revises: 1858db0c0b76
Create Date: 2026-08-25 07:58:11.511644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88702dc539a2'
down_revision: Union[str, Sequence[str], None] = '1858db0c0b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_class_ability_weapon_choices',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('ability_id', sa.UUID(), nullable=False),
    sa.Column('weapon_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['base_class_abilities.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['base_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'ability_id')
    )
    op.add_column('base_class_abilities', sa.Column('requires_weapon_choice', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_class_abilities', 'requires_weapon_choice')
    op.drop_table('character_class_ability_weapon_choices')
    # ### end Alembic commands ###
