"""add weapon special ability catalog and gear link

Revision ID: 8dd1fbfa0f90
Revises: fd9e4b803833
Create Date: 2026-08-03 23:42:16.474922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd1fbfa0f90'
down_revision: Union[str, Sequence[str], None] = 'fd9e4b803833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_weapon_special_abilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bonus_equivalent', sa.Integer(), nullable=True),
    sa.Column('applicable_categories', sa.JSON(), nullable=False),
    sa.Column('restriction_note', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_gear_special_abilities',
    sa.Column('gear_id', sa.UUID(), nullable=False),
    sa.Column('ability_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['base_weapon_special_abilities.id'], ),
    sa.ForeignKeyConstraint(['gear_id'], ['character_gear.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gear_id', 'ability_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_gear_special_abilities')
    op.drop_table('base_weapon_special_abilities')
    # ### end Alembic commands ###
