"""add feats, class abilities, and requirement tables

Revision ID: 8ed4b92b950d
Revises: dd82036f25f5
Create Date: 2026-07-30 15:21:18.176930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed4b92b950d'
down_revision: Union[str, Sequence[str], None] = 'dd82036f25f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_class_abilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_feats',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_class_ability_grants',
    sa.Column('base_class_id', sa.UUID(), nullable=False),
    sa.Column('ability_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['base_class_abilities.id'], ),
    sa.ForeignKeyConstraint(['base_class_id'], ['base_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_class_id', 'ability_id')
    )
    op.create_table('base_feat_required_ability_scores',
    sa.Column('feat_id', sa.UUID(), nullable=False),
    sa.Column('ability', sa.String(length=2), nullable=False),
    sa.Column('minimum_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feat_id'], ['base_feats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_feat_required_babs',
    sa.Column('feat_id', sa.UUID(), nullable=False),
    sa.Column('minimum_bab', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feat_id'], ['base_feats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_feat_required_class_abilities',
    sa.Column('feat_id', sa.UUID(), nullable=False),
    sa.Column('ability_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['base_class_abilities.id'], ),
    sa.ForeignKeyConstraint(['feat_id'], ['base_feats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_feat_required_class_levels',
    sa.Column('feat_id', sa.UUID(), nullable=False),
    sa.Column('base_class_id', sa.UUID(), nullable=False),
    sa.Column('minimum_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_class_id'], ['base_classes.id'], ),
    sa.ForeignKeyConstraint(['feat_id'], ['base_feats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_feat_required_feats',
    sa.Column('feat_id', sa.UUID(), nullable=False),
    sa.Column('required_feat_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feat_id'], ['base_feats.id'], ),
    sa.ForeignKeyConstraint(['required_feat_id'], ['base_feats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_feat_required_races',
    sa.Column('feat_id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feat_id'], ['base_feats.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['base_races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_feat_required_skills',
    sa.Column('feat_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('minimum_ranks', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feat_id'], ['base_feats.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['base_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_feats',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('feat_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feat_id'], ['base_feats.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['character_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'feat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_feats')
    op.drop_table('base_feat_required_skills')
    op.drop_table('base_feat_required_races')
    op.drop_table('base_feat_required_feats')
    op.drop_table('base_feat_required_class_levels')
    op.drop_table('base_feat_required_class_abilities')
    op.drop_table('base_feat_required_babs')
    op.drop_table('base_feat_required_ability_scores')
    op.drop_table('base_class_ability_grants')
    op.drop_table('base_feats')
    op.drop_table('base_class_abilities')
    # ### end Alembic commands ###
