"""add skill choice to traits

Revision ID: 95385060526f
Revises: 2f57b03b9f99
Create Date: 2026-08-21 23:11:55.264595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95385060526f'
down_revision: Union[str, Sequence[str], None] = '2f57b03b9f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_traits', sa.Column('skill_choice_ability', sa.String(length=2), nullable=True))
    op.add_column('character_traits', sa.Column('chosen_skill_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_character_traits_chosen_skill_id', 'character_traits', 'base_skills', ['chosen_skill_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_character_traits_chosen_skill_id', 'character_traits', type_='foreignkey')
    op.drop_column('character_traits', 'chosen_skill_id')
    op.drop_column('base_traits', 'skill_choice_ability')
    # ### end Alembic commands ###
