"""add target_item_id to character_effects

Revision ID: 979cd3153d40
Revises: 1065a369869e
Create Date: 2026-08-26 20:52:07.509573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979cd3153d40'
down_revision: Union[str, Sequence[str], None] = '1065a369869e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_effects', sa.Column('target_item_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'character_effects', 'base_items', ['target_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_effects', type_='foreignkey')
    op.drop_column('character_effects', 'target_item_id')
    # ### end Alembic commands ###
