"""add stat block fields to base_spells

Revision ID: a5c868344322
Revises: 0f0d3366600d
Create Date: 2026-08-21 10:46:34.901199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c868344322'
down_revision: Union[str, Sequence[str], None] = '0f0d3366600d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_spells', sa.Column('casting_time', sa.String(length=255), nullable=True))
    op.add_column('base_spells', sa.Column('range', sa.String(length=255), nullable=True))
    op.add_column('base_spells', sa.Column('target_or_area', sa.Text(), nullable=True))
    op.add_column('base_spells', sa.Column('duration', sa.String(length=255), nullable=True))
    op.add_column('base_spells', sa.Column('saving_throw', sa.String(length=255), nullable=True))
    op.add_column('base_spells', sa.Column('spell_resistance', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_spells', 'spell_resistance')
    op.drop_column('base_spells', 'saving_throw')
    op.drop_column('base_spells', 'duration')
    op.drop_column('base_spells', 'target_or_area')
    op.drop_column('base_spells', 'range')
    op.drop_column('base_spells', 'casting_time')
    # ### end Alembic commands ###
