"""add class ability feat and spell pool tables, class option choice fk fields, weapon group

Revision ID: a92f912d53bf
Revises: c382f0f50f1d
Create Date: 2026-08-01 15:00:43.723082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92f912d53bf'
down_revision: Union[str, Sequence[str], None] = 'c382f0f50f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_class_ability_feat_options',
    sa.Column('ability_id', sa.UUID(), nullable=False),
    sa.Column('option_choice_id', sa.UUID(), nullable=True),
    sa.Column('feat_type', sa.String(length=64), nullable=True),
    sa.Column('feat_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['base_class_abilities.id'], ),
    sa.ForeignKeyConstraint(['feat_id'], ['base_feats.id'], ),
    sa.ForeignKeyConstraint(['option_choice_id'], ['base_class_option_choices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_class_ability_spell_options',
    sa.Column('ability_id', sa.UUID(), nullable=False),
    sa.Column('option_choice_id', sa.UUID(), nullable=True),
    sa.Column('spell_id', sa.UUID(), nullable=True),
    sa.Column('source_class_id', sa.UUID(), nullable=True),
    sa.Column('source_grade', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['base_class_abilities.id'], ),
    sa.ForeignKeyConstraint(['option_choice_id'], ['base_class_option_choices.id'], ),
    sa.ForeignKeyConstraint(['source_class_id'], ['base_classes.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['base_spells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_class_spell_grants',
    sa.Column('base_class_id', sa.UUID(), nullable=False),
    sa.Column('option_choice_id', sa.UUID(), nullable=True),
    sa.Column('spell_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_class_id'], ['base_classes.id'], ),
    sa.ForeignKeyConstraint(['option_choice_id'], ['base_class_option_choices.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['base_spells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_class_id', 'option_choice_id', 'spell_id', 'level')
    )
    op.add_column('base_items', sa.Column('weapon_group', sa.String(length=64), nullable=True))
    op.add_column('character_class_options', sa.Column('level_id', sa.UUID(), nullable=True))
    op.add_column('character_class_options', sa.Column('grant_id', sa.UUID(), nullable=True))
    op.add_column('character_class_options', sa.Column('choice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'character_class_options', 'base_class_ability_grants', ['grant_id'], ['id'])
    op.create_foreign_key(None, 'character_class_options', 'character_levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'character_class_options', 'base_class_option_choices', ['choice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_class_options', type_='foreignkey')
    op.drop_constraint(None, 'character_class_options', type_='foreignkey')
    op.drop_constraint(None, 'character_class_options', type_='foreignkey')
    op.drop_column('character_class_options', 'choice_id')
    op.drop_column('character_class_options', 'grant_id')
    op.drop_column('character_class_options', 'level_id')
    op.drop_column('base_items', 'weapon_group')
    op.drop_table('base_class_spell_grants')
    op.drop_table('base_class_ability_spell_options')
    op.drop_table('base_class_ability_feat_options')
    # ### end Alembic commands ###
