"""add waives_prerequisites to base_class_ability_feat_options

Revision ID: b07bdf6be99a
Revises: 20789db57ee4
Create Date: 2026-09-22 21:24:16.058222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07bdf6be99a'
down_revision: Union[str, Sequence[str], None] = '20789db57ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'base_class_ability_feat_options',
        sa.Column('waives_prerequisites', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('base_class_ability_feat_options', 'waives_prerequisites', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_class_ability_feat_options', 'waives_prerequisites')
    # ### end Alembic commands ###
