"""add chosen_skill_id_2 to character_feats

Revision ID: b222744b5d20
Revises: 433dcddc98b3
Create Date: 2026-09-08 22:21:31.441796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b222744b5d20'
down_revision: Union[str, Sequence[str], None] = '433dcddc98b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_feats', sa.Column('chosen_skill_id_2', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('character_feats_level_id_feat_id_chosen_weapon_id_chosen_sk_key'), 'character_feats', type_='unique')
    op.create_unique_constraint(None, 'character_feats', ['level_id', 'feat_id', 'chosen_weapon_id', 'chosen_skill_id', 'chosen_skill_id_2', 'chosen_spell_school'])
    op.create_foreign_key(None, 'character_feats', 'base_skills', ['chosen_skill_id_2'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_feats', type_='foreignkey')
    op.drop_constraint(None, 'character_feats', type_='unique')
    op.create_unique_constraint(op.f('character_feats_level_id_feat_id_chosen_weapon_id_chosen_sk_key'), 'character_feats', ['level_id', 'feat_id', 'chosen_weapon_id', 'chosen_skill_id', 'chosen_spell_school'], postgresql_nulls_not_distinct=False)
    op.drop_column('character_feats', 'chosen_skill_id_2')
    # ### end Alembic commands ###
