"""add secondary class initial pick flag to base class option groups

Revision ID: b38d0a60e077
Revises: 81b8186e80d6
Create Date: 2026-09-04 14:43:58.945993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38d0a60e077'
down_revision: Union[str, Sequence[str], None] = '81b8186e80d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_class_option_groups', sa.Column('is_secondary_class_initial_pick', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_class_option_groups', 'is_secondary_class_initial_pick')
    # ### end Alembic commands ###
