"""add default_duration_rounds to base_class_abilities

Revision ID: b4a2e4c4fcaf
Revises: 979cd3153d40
Create Date: 2026-08-26 21:39:00.310291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a2e4c4fcaf'
down_revision: Union[str, Sequence[str], None] = '979cd3153d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_class_abilities', sa.Column('default_duration_rounds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_class_abilities', 'default_duration_rounds')
    # ### end Alembic commands ###
