"""add type to base_conditions

Revision ID: b585b4104b22
Revises: c54a7a428aad
Create Date: 2026-08-05 18:06:40.823270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b585b4104b22'
down_revision: Union[str, Sequence[str], None] = 'c54a7a428aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Placeholder default backfills any existing rows (seeded before this
    # column existed); `app.seed.condition_seed` overwrites it with the real
    # per-row value on its next run, same two-step pattern as
    # bc08779c752d_add_trained_only_to_base_skills.py.
    op.add_column(
        'base_conditions',
        sa.Column('type', sa.String(length=32), nullable=False, server_default='condition'),
    )
    op.alter_column('base_conditions', 'type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_conditions', 'type')
    # ### end Alembic commands ###
