"""add trained_only to base_skills

Revision ID: bc08779c752d
Revises: d0132f0cb72a
Create Date: 2026-08-04 11:44:25.118543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc08779c752d'
down_revision: Union[str, Sequence[str], None] = 'd0132f0cb72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'base_skills',
        sa.Column('trained_only', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('base_skills', 'trained_only', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_skills', 'trained_only')
    # ### end Alembic commands ###
