"""add spell slot usage tracking

Revision ID: c08ef54b0f63
Revises: b38d0a60e077
Create Date: 2026-09-05 00:54:49.752255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08ef54b0f63'
down_revision: Union[str, Sequence[str], None] = 'b38d0a60e077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_spell_slot_usages',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('base_class_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('used_today', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_class_id'], ['base_classes.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'base_class_id', 'grade')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_spell_slot_usages')
    # ### end Alembic commands ###
