"""add base_class_ability_replacements table

Revision ID: c09f87a2a76f
Revises: 005957a8da7f
Create Date: 2026-07-31 18:04:51.493764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09f87a2a76f'
down_revision: Union[str, Sequence[str], None] = '005957a8da7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_class_ability_replacements',
    sa.Column('archetype_class_id', sa.UUID(), nullable=False),
    sa.Column('ability_id', sa.UUID(), nullable=False),
    sa.Column('replaces_grant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['base_class_abilities.id'], ),
    sa.ForeignKeyConstraint(['archetype_class_id'], ['base_classes.id'], ),
    sa.ForeignKeyConstraint(['replaces_grant_id'], ['base_class_ability_grants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_class_ability_replacements')
    # ### end Alembic commands ###
