"""add speed to base races

Revision ID: c1db7b240e9f
Revises: 9a42240d198a
Create Date: 2026-07-31 12:05:38.800375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1db7b240e9f'
down_revision: Union[str, Sequence[str], None] = '9a42240d198a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_races', sa.Column('speed', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_races', 'speed')
    # ### end Alembic commands ###
