"""add spell tables and casting ability/tradition columns

Revision ID: c2c1f53b71b2
Revises: 68f4e2737ce0
Create Date: 2026-07-31 00:29:09.607843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c1f53b71b2'
down_revision: Union[str, Sequence[str], None] = '68f4e2737ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_spells',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_class_spells',
    sa.Column('base_class_id', sa.UUID(), nullable=False),
    sa.Column('spell_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_class_id'], ['base_classes.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['base_spells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_class_id', 'spell_id')
    )
    op.create_table('base_class_spells_known',
    sa.Column('base_class_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_class_id'], ['base_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_class_id', 'level', 'grade')
    )
    op.create_table('base_spell_components',
    sa.Column('spell_id', sa.UUID(), nullable=False),
    sa.Column('tradition', sa.String(length=16), nullable=False),
    sa.Column('verbal', sa.Boolean(), nullable=False),
    sa.Column('somatic', sa.Boolean(), nullable=False),
    sa.Column('material', sa.Boolean(), nullable=False),
    sa.Column('material_description', sa.String(length=255), nullable=True),
    sa.Column('focus', sa.Boolean(), nullable=False),
    sa.Column('focus_description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spell_id'], ['base_spells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spell_id', 'tradition')
    )
    op.create_table('character_spells',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('base_class_id', sa.UUID(), nullable=False),
    sa.Column('spell_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_class_id'], ['base_classes.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['character_levels.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['base_spells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'base_class_id', 'spell_id')
    )
    op.add_column('base_classes', sa.Column('casting_ability', sa.String(length=2), nullable=True))
    op.add_column('base_classes', sa.Column('spell_tradition', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_classes', 'spell_tradition')
    op.drop_column('base_classes', 'casting_ability')
    op.drop_table('character_spells')
    op.drop_table('base_spell_components')
    op.drop_table('base_class_spells_known')
    op.drop_table('base_class_spells')
    op.drop_table('base_spells')
    # ### end Alembic commands ###
