"""add group_id to base_feat_required tables

Revision ID: c382f0f50f1d
Revises: 17f6379b0125
Create Date: 2026-08-01 10:33:46.000063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c382f0f50f1d'
down_revision: Union[str, Sequence[str], None] = '17f6379b0125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_feat_required_ability_scores', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('base_feat_required_babs', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('base_feat_required_class_abilities', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('base_feat_required_class_levels', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('base_feat_required_feats', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('base_feat_required_races', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('base_feat_required_skills', sa.Column('group_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_feat_required_skills', 'group_id')
    op.drop_column('base_feat_required_races', 'group_id')
    op.drop_column('base_feat_required_feats', 'group_id')
    op.drop_column('base_feat_required_class_levels', 'group_id')
    op.drop_column('base_feat_required_class_abilities', 'group_id')
    op.drop_column('base_feat_required_babs', 'group_id')
    op.drop_column('base_feat_required_ability_scores', 'group_id')
    # ### end Alembic commands ###
