"""add effects tables

Revision ID: c54a7a428aad
Revises: 65ba5c3da7b3
Create Date: 2026-08-05 09:47:16.657768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54a7a428aad'
down_revision: Union[str, Sequence[str], None] = '65ba5c3da7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_conditions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_effects',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('incubation_remaining', sa.Integer(), nullable=True),
    sa.Column('duration_remaining', sa.Integer(), nullable=True),
    sa.Column('frequency_rounds', sa.Integer(), nullable=True),
    sa.Column('next_check_in', sa.Integer(), nullable=True),
    sa.Column('successes_current', sa.Integer(), nullable=False),
    sa.Column('successes_required', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'base_class_abilities',
        sa.Column('is_persistent_effect', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('base_class_abilities', 'is_persistent_effect', server_default=None)
    op.add_column(
        'base_spells',
        sa.Column('is_persistent_effect', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('base_spells', 'is_persistent_effect', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_spells', 'is_persistent_effect')
    op.drop_column('base_class_abilities', 'is_persistent_effect')
    op.drop_table('character_effects')
    op.drop_table('base_conditions')
    # ### end Alembic commands ###
