"""add wondrous item fields to base_items and character_gear

Revision ID: d0132f0cb72a
Revises: 8dd1fbfa0f90
Create Date: 2026-08-04 10:03:13.724134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0132f0cb72a'
down_revision: Union[str, Sequence[str], None] = '8dd1fbfa0f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_items', sa.Column('slot', sa.String(length=32), nullable=True))
    op.add_column('base_items', sa.Column('activation', sa.String(length=16), nullable=True))
    op.add_column('base_items', sa.Column('uses_per_day', sa.Integer(), nullable=True))
    op.add_column('base_items', sa.Column('max_charges', sa.Integer(), nullable=True))
    op.add_column('base_items', sa.Column('granted_ability', sa.String(length=16), nullable=True))
    op.add_column('base_items', sa.Column('ability_bonus', sa.Integer(), nullable=True))
    op.add_column('character_gear', sa.Column('stored_spell_id', sa.UUID(), nullable=True))
    op.add_column('character_gear', sa.Column('charges_remaining', sa.Integer(), nullable=True))
    op.add_column('character_gear', sa.Column('uses_remaining_today', sa.Integer(), nullable=True))
    op.add_column('character_gear', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('character_gear', 'is_active', server_default=None)
    op.create_foreign_key(None, 'character_gear', 'base_spells', ['stored_spell_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_gear', type_='foreignkey')
    op.drop_column('character_gear', 'is_active')
    op.drop_column('character_gear', 'uses_remaining_today')
    op.drop_column('character_gear', 'charges_remaining')
    op.drop_column('character_gear', 'stored_spell_id')
    op.drop_column('base_items', 'ability_bonus')
    op.drop_column('base_items', 'granted_ability')
    op.drop_column('base_items', 'max_charges')
    op.drop_column('base_items', 'uses_per_day')
    op.drop_column('base_items', 'activation')
    op.drop_column('base_items', 'slot')
    # ### end Alembic commands ###
