"""allow repeated class ability grants at different levels

Revision ID: d925ead90c76
Revises: 62ebc8000faf
Create Date: 2026-07-30 23:14:14.074944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd925ead90c76'
down_revision: Union[str, Sequence[str], None] = '62ebc8000faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('base_class_ability_grants_base_class_id_ability_id_option_c_key'), 'base_class_ability_grants', type_='unique')
    op.create_unique_constraint(None, 'base_class_ability_grants', ['base_class_id', 'ability_id', 'option_choice_id', 'level'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'base_class_ability_grants', type_='unique')
    op.create_unique_constraint(op.f('base_class_ability_grants_base_class_id_ability_id_option_c_key'), 'base_class_ability_grants', ['base_class_id', 'ability_id', 'option_choice_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
