"""add skill points base column to base classes

Revision ID: dc0c837e77bb
Revises: fa831e2478e2
Create Date: 2026-07-31 10:18:05.047306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0c837e77bb'
down_revision: Union[str, Sequence[str], None] = 'fa831e2478e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_classes', sa.Column('skill_points_base', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_classes', 'skill_points_base')
    # ### end Alembic commands ###
