"""add bab progression and save columns to base classes

Revision ID: fa831e2478e2
Revises: c2c1f53b71b2
Create Date: 2026-07-31 10:03:15.704473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa831e2478e2'
down_revision: Union[str, Sequence[str], None] = 'c2c1f53b71b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_classes', sa.Column('bab_progression', sa.Float(), nullable=True))
    op.add_column('base_classes', sa.Column('fort_save', sa.Boolean(), nullable=True))
    op.add_column('base_classes', sa.Column('ref_save', sa.Boolean(), nullable=True))
    op.add_column('base_classes', sa.Column('wil_save', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_classes', 'wil_save')
    op.drop_column('base_classes', 'ref_save')
    op.drop_column('base_classes', 'fort_save')
    op.drop_column('base_classes', 'bab_progression')
    # ### end Alembic commands ###
