"""add weapon combat stat fields to base items

Revision ID: fd9e4b803833
Revises: 6480e4dfea03
Create Date: 2026-08-03 15:07:46.004689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9e4b803833'
down_revision: Union[str, Sequence[str], None] = '6480e4dfea03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_items', sa.Column('damage_small', sa.String(length=32), nullable=True))
    op.add_column('base_items', sa.Column('damage_medium', sa.String(length=32), nullable=True))
    op.add_column('base_items', sa.Column('critical', sa.String(length=32), nullable=True))
    op.add_column('base_items', sa.Column('weapon_range', sa.String(length=32), nullable=True))
    op.add_column('base_items', sa.Column('damage_type', sa.String(length=32), nullable=True))
    op.add_column('base_items', sa.Column('weapon_type', sa.String(length=32), nullable=True))
    op.add_column('base_items', sa.Column('special', sa.String(length=255), nullable=True))
    op.add_column('base_items', sa.Column('weight_lb', sa.String(length=32), nullable=True))
    op.add_column('base_items', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_items', 'description')
    op.drop_column('base_items', 'weight_lb')
    op.drop_column('base_items', 'special')
    op.drop_column('base_items', 'weapon_type')
    op.drop_column('base_items', 'damage_type')
    op.drop_column('base_items', 'weapon_range')
    op.drop_column('base_items', 'critical')
    op.drop_column('base_items', 'damage_medium')
    op.drop_column('base_items', 'damage_small')
    # ### end Alembic commands ###
