"""Populates `base_feats` and the six `BaseFeatRequired*` prerequisite tables
from `backend/app/fixtures/seed/base_feats.json` +
`base_feat_required_{feats,skills,class_levels,class_abilities,races,
ability_scores,babs}.json` — DB-shaped, one row per requirement with an
explicit `id`, same convention as `race_seed.py`/`class_seed.py`/
`skill_seed.py`. Replaces the old frontend-shaped
`backend/app/fixtures/feats.json` (superseded, not deleted). Generated by
`backend/scripts/build_feats_seed.py` from the bulk PRD import — see that
script's docstring for scope/reconciliation/parsing decisions.

Idempotent: each row is upserted by its own `id`, safe to re-run. Requires
`base_races`/`base_classes`/`base_class_abilities`/`base_skills` to already
be seeded (FK targets for the requirement tables), and `base_feats` itself
seeded before `base_feat_required_feats` (self-referencing).

Run with the project venv active and the database up:
    cd backend && python -m app.seed.feat_seed
"""

import json
from pathlib import Path
from uuid import UUID

from sqlalchemy.orm import Session

from ..models.feat import (
    BaseFeat,
    BaseFeatRequiredAbilityScore,
    BaseFeatRequiredBab,
    BaseFeatRequiredClassAbility,
    BaseFeatRequiredClassLevel,
    BaseFeatRequiredFeat,
    BaseFeatRequiredRace,
    BaseFeatRequiredSkill,
)

SEED_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "seed"


def _load(filename: str) -> list[dict]:
    return json.loads((SEED_DIR / filename).read_text(encoding="utf-8"))


def _upsert(db: Session, model: type, row: dict, *, uuid_fields: tuple[str, ...] = ()) -> None:
    """`uuid_fields` covers both FKs and the plain `group_id` correlation
    column (see `BaseFeatRequiredFeat.group_id`) — anything stored as a UUID
    that arrives as a string in the JSON fixture. None-safe, since group_id
    is nullable (most requirement rows aren't part of an OR-group)."""
    row_id = UUID(row["id"])
    fields = {
        k: (UUID(v) if (k in uuid_fields and v is not None) else v)
        for k, v in row.items()
        if k != "id"
    }
    instance = db.get(model, row_id)
    if instance is None:
        db.add(model(id=row_id, **fields))
    else:
        for key, value in fields.items():
            setattr(instance, key, value)


def seed_feats(db: Session) -> None:
    for row in _load("base_feats.json"):
        _upsert(db, BaseFeat, row)
    db.flush()

    for row in _load("base_feat_required_feats.json"):
        _upsert(db, BaseFeatRequiredFeat, row, uuid_fields=("feat_id", "required_feat_id", "group_id"))
    for row in _load("base_feat_required_skills.json"):
        _upsert(db, BaseFeatRequiredSkill, row, uuid_fields=("feat_id", "skill_id", "group_id"))
    for row in _load("base_feat_required_class_levels.json"):
        _upsert(db, BaseFeatRequiredClassLevel, row, uuid_fields=("feat_id", "base_class_id", "group_id"))
    for row in _load("base_feat_required_class_abilities.json"):
        _upsert(db, BaseFeatRequiredClassAbility, row, uuid_fields=("feat_id", "ability_id", "group_id"))
    for row in _load("base_feat_required_races.json"):
        _upsert(db, BaseFeatRequiredRace, row, uuid_fields=("feat_id", "race_id", "group_id"))
    for row in _load("base_feat_required_ability_scores.json"):
        _upsert(db, BaseFeatRequiredAbilityScore, row, uuid_fields=("feat_id", "group_id"))
    for row in _load("base_feat_required_babs.json"):
        _upsert(db, BaseFeatRequiredBab, row, uuid_fields=("feat_id", "group_id"))

    db.commit()


def main() -> None:
    from ..db import SessionLocal

    db = SessionLocal()
    try:
        seed_feats(db)
    finally:
        db.close()


if __name__ == "__main__":
    main()
